packageURL <- "https://cran.r-project.org/src/contrib/Archive/EcoHydRology/EcoHydRology_0.4.12.1.tar.gz"
install.packages(packageURL, repos=NULL, type="source")

library(AOI)
library(climateR)
library(data.table)
library(dataRetrieval)
library(dplyr)
library(EcoHydRology)
library(exactextractr)
library(ggplot2)
library(here)
library(lubridate)
library(raster)
library(readr)
library(renv)
library(rmarkdown)
library(sf)
library(sp)
library(stringr)
library(stringr)
library(sf)
library(tidyverse)
library(terra)
library(elevatr)
library(boot)
library(xgboost)
library(caret)
library(ggthemes)
library(hydroGOF)
